services:
  - type: web
    name: pdf-tools-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 200
    plan: free
    region: oregon
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - apt.txt
        - build.sh
    envVars:
      PYTHONUNBUFFERED: true
    packages:
      apt:
        - libreoffice
        - poppler-utils
